In [2]:
# Boosting Algorithm - XGBoost for a classification problem
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.datasets import load_iris

In [11]:
# importing data into pandas dataframe
df = load_iris()


In [12]:
features = df.data
target = df.target

In [44]:
features.shape, target.shape

((150, 4), (150,))

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size = 0.3, random_state=1)

In [47]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [48]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
my_model1 = DecisionTreeClassifier()

In [50]:
my_model1.fit(x_train,y_train)
my_model1_preds = my_model1.predict(x_test)

In [51]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [53]:
print(accuracy_score(y_test, my_model1_preds))

0.9555555555555556


In [55]:
print(confusion_matrix(y_test, my_model1_preds))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


In [56]:
from sklearn.ensemble import AdaBoostClassifier

In [57]:
my_ada_clf = AdaBoostClassifier()

In [58]:
my_ada_clf.fit(x_train,y_train)
my_ada_preds = my_ada_clf.predict(x_test)

In [59]:
print(accuracy_score(y_test, my_ada_preds))

0.9555555555555556


In [60]:
from sklearn.ensemble import GradientBoostingClassifier

In [61]:
my_gb_clf = GradientBoostingClassifier()

In [63]:
my_gb_clf.fit(x_train, y_train)

GradientBoostingClassifier()

In [64]:
my_gb_preds = my_gb_clf.predict(x_test)

In [65]:
print(accuracy_score(y_test, my_gb_preds))

0.9555555555555556


In [33]:
#pip install xgboost

In [66]:
from xgboost import XGBClassifier

In [68]:
my_xgb_clf = XGBClassifier(booster = 'gbtree')
my_xgb_clf.fit(x_train, y_train)

[21:19:04] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [69]:
my_xgb_preds = my_xgb_clf.predict(x_test)

In [70]:
print(accuracy_score(y_test, my_xgb_preds))

0.9555555555555556
