In [3]:
from sklearn.datasets import load_digits
import numpy as np
import pandas as pd

In [4]:
df = load_digits()


In [5]:
df.DESCR.split('\n')

['.. _digits_dataset:',
 '',
 'Optical recognition of handwritten digits dataset',
 '--------------------------------------------------',
 '',
 '**Data Set Characteristics:**',
 '',
 '    :Number of Instances: 5620',
 '    :Number of Attributes: 64',
 '    :Attribute Information: 8x8 image of integer pixels in the range 0..16.',
 '    :Missing Attribute Values: None',
 "    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)",
 '    :Date: July; 1998',
 '',
 'This is a copy of the test set of the UCI ML hand-written digits datasets',
 'https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits',
 '',
 'The data set contains images of hand-written digits: 10 classes where',
 'each class refers to a digit.',
 '',
 'Preprocessing programs made available by NIST were used to extract',
 'normalized bitmaps of handwritten digits from a preprinted form. From a',
 'total of 43 people, 30 contributed to the training set and different 13',
 'to the test set. 32x32 bitmaps are

In [7]:
features = df.data
target = df.target

In [8]:
features.shape,target.shape

((1797, 64), (1797,))

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [14]:
X_train, X_test, y_train, y_test = train_test_split(features, target, train_size = 0.6, random_state = 3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1078, 64)
(719, 64)
(1078,)
(719,)


In [15]:
my_model = LogisticRegression()

In [16]:
my_model.fit(X_train,y_train)

LogisticRegression()

In [17]:
preds = my_model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [19]:
print(accuracy_score(y_test, preds))

0.9582753824756607


In [20]:
print(confusion_matrix(y_test, preds))

[[74  0  0  0  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  2  1]
 [ 0  1 77  0  0  0  0  0  0  0]
 [ 0  0  2 66  0  0  0  0  1  0]
 [ 0  4  0  0 79  0  1  1  1  0]
 [ 0  1  0  0  1 60  0  0  0  2]
 [ 0  1  0  0  0  1 55  0  1  0]
 [ 0  0  0  1  0  0  0 73  2  0]
 [ 0  1  0  0  0  1  0  0 66  0]
 [ 0  0  0  0  1  1  0  0  1 67]]


In [21]:
import seaborn as sns

In [26]:
from sklearn.decomposition import PCA

In [30]:
pca = PCA(n_components=.95)

In [31]:
pca.fit(X_train)

PCA(n_components=0.95)

In [33]:
pca.explained_variance_ratio_.shape # not a good pca example

(28,)