In [4]:
from sklearn.datasets import load_iris

In [5]:
import pandas as pd
import numpy as np

In [6]:
data = load_iris()

In [7]:
data.DESCR.split('\n')

['.. _iris_dataset:',
 '',
 'Iris plants dataset',
 '--------------------',
 '',
 '**Data Set Characteristics:**',
 '',
 '    :Number of Instances: 150 (50 in each of three classes)',
 '    :Number of Attributes: 4 numeric, predictive attributes and the class',
 '    :Attribute Information:',
 '        - sepal length in cm',
 '        - sepal width in cm',
 '        - petal length in cm',
 '        - petal width in cm',
 '        - class:',
 '                - Iris-Setosa',
 '                - Iris-Versicolour',
 '                - Iris-Virginica',
 '                ',
 '    :Summary Statistics:',
 '',
 '    ============== ==== ==== ======= ===== ====================',
 '                    Min  Max   Mean    SD   Class Correlation',
 '    ============== ==== ==== ======= ===== ====================',
 '    sepal length:   4.3  7.9   5.84   0.83    0.7826',
 '    sepal width:    2.0  4.4   3.05   0.43   -0.4194',
 '    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)',
 '    pe

In [8]:
features = data.data
target = data.target
features.shape, target.shape

((150, 4), (150,))

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(features, target, train_size = 0.8, random_state = 3)

In [11]:
from sklearn.linear_model import LogisticRegression

In [13]:
my_model = LogisticRegression()

In [14]:
my_model.fit(X_train,y_train)

C:\Users\adhik\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
preds = my_model.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [17]:
print(accuracy_score(y_test,preds))

1.0


In [18]:
print(confusion_matrix(y_test,preds))

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [19]:
from sklearn.decomposition import PCA

In [20]:
pca = PCA(n_components=2)

In [21]:
pca.fit(X_train)

PCA(n_components=2)

In [28]:
X_train_transformed = pca.transform(X_train)

In [29]:
pca.explained_variance_ratio_

array([0.92534735, 0.05176554])

In [30]:
X_test_transformed = pca.transform(X_test)

In [31]:
my_model.fit(X_train_transformed, y_train)

LogisticRegression()

In [32]:
preds_pca = my_model.predict(X_test_transformed)

In [33]:
print(accuracy_score(y_test, preds_pca))

0.9666666666666667


In [34]:
print(confusion_matrix(y_test, preds_pca))

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
